### ISSUE TITLE
Difficulty System

### ISSUE THREAD

**Issue by ralflaurenzo** [rluop/comp-55-final-project-fork#1]
Currently, the game only starts from "Stage 1" where the blocks move very slowly before their speed starts ramping up. In other iterations from Tetris, this is not the case. This can be done by adding an extra button in the main menu underneath the original start button that will lead the player to another screen, similar to the Controls button. This screen will have more buttons with set difficulties that allow you to start the game at a different stage. In the game's code exists a StartGame function that simply starts the game by initializing lots of other functions, and while it will remain largely the same, it will also return a value that will indicate the stage the player wants to begin at, which is determined by the button that is clicked on by the player. This value will be passed from the StartGame function to the function that handles the falling speed of the blocks and will directly modify their values via use of switch cases. The game will run as expected afterwards.

**Comment by onzfonz** [comment]
I'm ok with you doing this, but with the added priority of having the difficulty stored into a file instead, so that it perhaps stores the difficulty and loads it in on each playthrough.
Start with the file and then if you get to a setting where it can be changed, then that would be icing on the cake.

**Comment by ralflaurenzo** [comment]
feature implemented
